#! /usr/bin/env python3
import gspread
import slack_bolt
import datetime
from oauth2client.service_account import ServiceAccountCredentials

scope = [
    'https://www.googleapis.com/auth/drive',
    'https://www.googleapis.com/auth/drive.file'
]

url = 'https://docs.google.com/spreadsheets/d/1AHSiG8pJN5wZjg84mqOV3HsCXf8_3yNSRRp7Fk2utiM'
key = 'phillyhc-client-key.json'
creds = ServiceAccountCredentials.from_json_keyfile_name(key, scope)
client = gspread.authorize(creds)
sheet = client.open_by_url(url)

autogenerated = sheet.get_worksheet(1).get_all_records()
slack_user_ids = sheet.get_worksheet(3).get_all_records()

channel_id = "GULQKKBRB"

app = slack_bolt.App(
    token="<snipped>",
    signing_secret="<snipped>",
)


def main():
    next_friday = next_weekday(datetime.date.today(), 4)
    pair = next_pair(next_friday, autogenerated)

    message = ""

    if pair["People"] == "No Cell":
        message = f"No cell this week! Event: {pair['Event']}"

    else:
        person1, person2 = pair["People"].split("/")

        person1_id = [ p["Slack User ID"] for p in slack_user_ids if p["Name"] == person1 ][0]
        person2_id = [ p["Slack User ID"] for p in slack_user_ids if p["Name"] == person2 ][0]

        message = f"<@{person1_id}> and <@{person2_id}> are on cell dinner this week!"

    app.client.chat_postMessage(
        channel=channel_id,
        text=message,
    )


def next_weekday(d, weekday):
    days_ahead = weekday - d.weekday()
    if days_ahead <= 0: # Target day already happened this week
        days_ahead += 7
    return d + datetime.timedelta(days_ahead)


def next_pair(d, rotation):
    for pair in rotation:
        date = datetime.datetime.strptime(pair["Date"], "%Y-%m-%d").date()
        if date == d:
            return pair


if __name__ == "__main__":
    main()
